### ISSUE TITLE
How to find out the latitude and longitude?

### ISSUE THREAD

**Issue by manmeet3591** [laishenggx/GSMaP#1]
From you code

gz = gzip.GzipFile(filename1,'rb')
dd=np.frombuffer(gz.read(),dtype=np.float32)
print(dd[:100])

How to know for what latitude and longitude the data is corresponding to?

**Comment by laishenggx** [comment]
JAXA provides the geo-information of each GSMap products:
https://sharaku.eorc.jaxa.jp/GSMaP/faq/GSMaP_faq18.html
Fig.1 shows the coverage, row/column and the key points of the grid.
![fig1](https://user-images.githubusercontent.com/47738665/103637126-f84d6b00-4f85-11eb-9185-7fcef9f154b2.png)

You can also get .ctl example files directly from a folder named /sample/ on the JAXA's datasever:
(Example: /realtime_ver/v6/sample/GSMaP_NRT.daily0.1.p12Z-11Z.ctl)
> DSET ^gsmap_nrt.%y4%m2%d2.0.1d.daily.p12Z-11Z.dat
> TITLE GSMaP_NRT 0.1deg Daily (12:00Z(previous day)-11:59Z)
> UNDEF -999.9
> OPTIONS YREV LITTLE_ENDIAN TEMPLATE
> XDEF   3600 LINEAR  0.05 0.1
> YDEF   1200  LINEAR -59.95 0.1
> zdef 1 levels 1013
> tdef 3650 linear 00:00z1dec2007 1dy
> VARS 1
> precip          0 99 daily averaged precip(mm/hr)
> ENDVARS

As shown in the CTL file, geo-information was defined by XDEF and YDEF.
If you know somethings about GrADS, you can understand the exact meaning of `XDEF  3600 LINEAR  0.05 0.1` is `X-axis of this grid has 3600 points, it starts at 0.05 and the interval is 0.1 degrees.`
Thus you can use numpy.arange or numpy.linspace to arrange longitude:

> lon=np.linspace(0.05,359.95,3600)

Latitude is the same. But I think there is a mistake in the CTL file, it describes the latitude is from SOUTH to NORTH, as opposed to the Fig.1.
I check out the datafile, the result shows that the description of Fig.1 is correct.

> lat=np.linspace(59.95,-59.95,1200)

Last but not least, I suggest you use xarray to manage data which you read from these raw files.

**Comment by manmeet3591** [comment]
Thank you so much. Somehow I had resolved that error and have got in the following 

I am trying to make netcdf data out of the binary GSMAP datasets using a python script similar to https://wiki.mpimet.mpg.de/doku.php?id=analysis:pot_pourri:processing_binary_data

I am using the hokusai.eorc.jaxa.jp/standard/v6/hourly/2002/01/01/gsmap_rnl.20020101.0000.v6.5133.0.dat.gz

as a test dataset and read it to a variable. The read variable is then reashaped to a 2D using numpy reshape function. However, I am getting an error as follows

ValueError: cannot reshape array of size 320907 into shape (1200,3600)

I tried with another file (hokusai.eorc.jaxa.jp/standard/v6/hourly/2002/01/01/gsmap_rnl.20020201.0000.v6.5133.0.dat.gz
) as well and got a similar error

ValueError: cannot reshape array of size 296288 into shape (1200,3600)

I am unable to understand how can the number of datapoints be different than 1200*3600. 

Can you please help me with this?

**Comment by laishenggx** [comment]
I download the same file (hokusai.eorc.jaxa.jp/standard/v6/hourly/2002/01/01/gsmap_rnl.20020101.0000.v6.5133.0.dat.gz)
and use the same numpy method to read out those datas, it works for me.
![test](https://user-images.githubusercontent.com/47738665/103643409-98f45880-4f8f-11eb-83e3-ec5e5479cc79.png)

I would upload some scripts to this project's repositories:
1.  gsmap_reader.py: script makes the figure shown above.
2.  gsmap_grib2nc.py: script to read out daily data(/realtime_ver/v6/daily_G/p12Z-11Z/), and put the into netCDF4 file for each year.

I would have known the reasons why the scripts from MPI wiki did not properly work, if I checked their script deeply.

**Comment by manmeet3591** [comment]
Thanks. This worked awesome.
